// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    [Migration("20220301151452_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("WebApplication1.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<int>("Status");

                    b.Property<int?>("sellerId");

                    b.HasKey("Id");

                    b.HasIndex("sellerId");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("WebApplication1.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int?>("departmentid");

                    b.HasKey("Id");

                    b.HasIndex("departmentid");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("WebApplication1.Models.SalesRecord", b =>
                {
                    b.HasOne("WebApplication1.Models.Seller", "seller")
                        .WithMany("sales")
                        .HasForeignKey("sellerId");
                });

            modelBuilder.Entity("WebApplication1.Models.Seller", b =>
                {
                    b.HasOne("WebApplication1.Models.Department", "department")
                        .WithMany("Sellers")
                        .HasForeignKey("departmentid");
                });
#pragma warning restore 612, 618
        }
    }
}
